### ISSUE TITLE
Server crash at startup (1.8.9)

### ISSUE THREAD

**Issue by kwpugh** [MikeLydeamore/SimpleLabels#7] opened 2016-01-28 15:00 UTC
1.8.9 server crashes at start when mod is added.

Crash report:  http://pastebin.com/raw/cfyWkzxW

**Comment by MikeLydeamore** [comment] 2016-01-28 22:50
Fixed in d0ac8a07afd913793f38318241f1b536a55de2df v0.03. Duplicate of #6.

**Closed as completed by MikeLydeamore** 2016-01-28 22:50 UTC

**Comment by kwpugh** [comment] 2016-01-29 00:36
Did you mean to hard-code this to run on only forge 1724?   I'm have 1726 and it crashes with a message that it requires 1724.

**Comment by tterrag1098** [comment] 2016-01-29 00:58
That shouldn't be the case, could you post your log?

**Comment by kwpugh** [comment] 2016-01-29 01:12
Crash report:  http://pastebin.com/raw/iQSR9vpp

**Comment by MikeLydeamore** [comment] 2016-01-29 01:24
Should be fixed again in a5bdf65a61bbe0020cdd0251b73ce6007c9d5e18 v0.0.4
